Spring:
  application:
    name: chap06-file-upload-lecture-source

  servlet:
    multipart:
      location: /Users/xogud # 파일 저장 경로
      max-file-size: 10MB # 최대 업로드 파일 크기
      max-request-size: 10MB # 최대 요청 파일 크기

